/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace DigitalLegacyVault {
      
    export type VaultStruct = {owner: AddressLike, beneficiary: AddressLike, secretDataOrIpfs: string, pingInterval: BigNumberish, lastPing: BigNumberish, requiredApprovals: BigNumberish, currentApprovals: BigNumberish, isReleased: boolean, isCanceled: boolean}

    export type VaultStructOutput = [owner: string, beneficiary: string, secretDataOrIpfs: string, pingInterval: bigint, lastPing: bigint, requiredApprovals: bigint, currentApprovals: bigint, isReleased: boolean, isCanceled: boolean] & {owner: string, beneficiary: string, secretDataOrIpfs: string, pingInterval: bigint, lastPing: bigint, requiredApprovals: bigint, currentApprovals: bigint, isReleased: boolean, isCanceled: boolean }
  
    }

  export interface DigitalLegacyVaultInterface extends Interface {
    getFunction(nameOrSignature: "cancelVault" | "checkIn" | "createVault" | "getTrustees" | "getVault" | "hasApproved" | "isExpired" | "isTrustee" | "release" | "trusteeApprove" | "vaultCount" | "vaults"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CheckedIn" | "TrusteeApproved" | "VaultCanceled" | "VaultCreated" | "VaultReleased"): EventFragment;

    encodeFunctionData(functionFragment: 'cancelVault', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'checkIn', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createVault', values: [AddressLike, AddressLike[], BigNumberish, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'getTrustees', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getVault', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'hasApproved', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'isExpired', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'isTrustee', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'release', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'trusteeApprove', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'vaultCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'vaults', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'cancelVault', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'checkIn', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createVault', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTrustees', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getVault', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasApproved', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isExpired', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isTrustee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'release', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'trusteeApprove', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vaultCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vaults', data: BytesLike): Result;
  }

  
    export namespace CheckedInEvent {
      export type InputTuple = [vaultId: BigNumberish, newLastPing: BigNumberish];
      export type OutputTuple = [vaultId: bigint, newLastPing: bigint];
      export interface OutputObject {vaultId: bigint, newLastPing: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TrusteeApprovedEvent {
      export type InputTuple = [vaultId: BigNumberish, trustee: AddressLike, totalApprovals: BigNumberish];
      export type OutputTuple = [vaultId: bigint, trustee: string, totalApprovals: bigint];
      export interface OutputObject {vaultId: bigint, trustee: string, totalApprovals: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VaultCanceledEvent {
      export type InputTuple = [vaultId: BigNumberish];
      export type OutputTuple = [vaultId: bigint];
      export interface OutputObject {vaultId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VaultCreatedEvent {
      export type InputTuple = [vaultId: BigNumberish, owner: AddressLike, beneficiary: AddressLike, pingInterval: BigNumberish];
      export type OutputTuple = [vaultId: bigint, owner: string, beneficiary: string, pingInterval: bigint];
      export interface OutputObject {vaultId: bigint, owner: string, beneficiary: string, pingInterval: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VaultReleasedEvent {
      export type InputTuple = [vaultId: BigNumberish, secretDataOrIpfs: string, beneficiary: AddressLike];
      export type OutputTuple = [vaultId: bigint, secretDataOrIpfs: string, beneficiary: string];
      export interface OutputObject {vaultId: bigint, secretDataOrIpfs: string, beneficiary: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface DigitalLegacyVault extends BaseContract {
    
    connect(runner?: ContractRunner | null): DigitalLegacyVault;
    waitForDeployment(): Promise<this>;

    interface: DigitalLegacyVaultInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    cancelVault: TypedContractMethod<
      [_vaultId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    checkIn: TypedContractMethod<
      [_vaultId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    createVault: TypedContractMethod<
      [_beneficiary: AddressLike, _trustees: AddressLike[], _requiredApprovals: BigNumberish, _pingInterval: BigNumberish, _secretDataOrIpfs: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    getTrustees: TypedContractMethod<
      [_vaultId: BigNumberish, ],
      [string[]],
      'view'
    >
    

    
    getVault: TypedContractMethod<
      [_vaultId: BigNumberish, ],
      [DigitalLegacyVault.VaultStructOutput],
      'view'
    >
    

    
    hasApproved: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isExpired: TypedContractMethod<
      [_vaultId: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    isTrustee: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    release: TypedContractMethod<
      [_vaultId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    trusteeApprove: TypedContractMethod<
      [_vaultId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    vaultCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    vaults: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, string, bigint, bigint, bigint, bigint, boolean, boolean] & {owner: string, beneficiary: string, secretDataOrIpfs: string, pingInterval: bigint, lastPing: bigint, requiredApprovals: bigint, currentApprovals: bigint, isReleased: boolean, isCanceled: boolean }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'cancelVault'): TypedContractMethod<
      [_vaultId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'checkIn'): TypedContractMethod<
      [_vaultId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createVault'): TypedContractMethod<
      [_beneficiary: AddressLike, _trustees: AddressLike[], _requiredApprovals: BigNumberish, _pingInterval: BigNumberish, _secretDataOrIpfs: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getTrustees'): TypedContractMethod<
      [_vaultId: BigNumberish, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getVault'): TypedContractMethod<
      [_vaultId: BigNumberish, ],
      [DigitalLegacyVault.VaultStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'hasApproved'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isExpired'): TypedContractMethod<
      [_vaultId: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isTrustee'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'release'): TypedContractMethod<
      [_vaultId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'trusteeApprove'): TypedContractMethod<
      [_vaultId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'vaultCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'vaults'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, string, bigint, bigint, bigint, bigint, boolean, boolean] & {owner: string, beneficiary: string, secretDataOrIpfs: string, pingInterval: bigint, lastPing: bigint, requiredApprovals: bigint, currentApprovals: bigint, isReleased: boolean, isCanceled: boolean }],
      'view'
    >;

    getEvent(key: 'CheckedIn'): TypedContractEvent<CheckedInEvent.InputTuple, CheckedInEvent.OutputTuple, CheckedInEvent.OutputObject>;
getEvent(key: 'TrusteeApproved'): TypedContractEvent<TrusteeApprovedEvent.InputTuple, TrusteeApprovedEvent.OutputTuple, TrusteeApprovedEvent.OutputObject>;
getEvent(key: 'VaultCanceled'): TypedContractEvent<VaultCanceledEvent.InputTuple, VaultCanceledEvent.OutputTuple, VaultCanceledEvent.OutputObject>;
getEvent(key: 'VaultCreated'): TypedContractEvent<VaultCreatedEvent.InputTuple, VaultCreatedEvent.OutputTuple, VaultCreatedEvent.OutputObject>;
getEvent(key: 'VaultReleased'): TypedContractEvent<VaultReleasedEvent.InputTuple, VaultReleasedEvent.OutputTuple, VaultReleasedEvent.OutputObject>;

    filters: {
      
      'CheckedIn(uint256,uint256)': TypedContractEvent<CheckedInEvent.InputTuple, CheckedInEvent.OutputTuple, CheckedInEvent.OutputObject>;
      CheckedIn: TypedContractEvent<CheckedInEvent.InputTuple, CheckedInEvent.OutputTuple, CheckedInEvent.OutputObject>;
    

      'TrusteeApproved(uint256,address,uint8)': TypedContractEvent<TrusteeApprovedEvent.InputTuple, TrusteeApprovedEvent.OutputTuple, TrusteeApprovedEvent.OutputObject>;
      TrusteeApproved: TypedContractEvent<TrusteeApprovedEvent.InputTuple, TrusteeApprovedEvent.OutputTuple, TrusteeApprovedEvent.OutputObject>;
    

      'VaultCanceled(uint256)': TypedContractEvent<VaultCanceledEvent.InputTuple, VaultCanceledEvent.OutputTuple, VaultCanceledEvent.OutputObject>;
      VaultCanceled: TypedContractEvent<VaultCanceledEvent.InputTuple, VaultCanceledEvent.OutputTuple, VaultCanceledEvent.OutputObject>;
    

      'VaultCreated(uint256,address,address,uint256)': TypedContractEvent<VaultCreatedEvent.InputTuple, VaultCreatedEvent.OutputTuple, VaultCreatedEvent.OutputObject>;
      VaultCreated: TypedContractEvent<VaultCreatedEvent.InputTuple, VaultCreatedEvent.OutputTuple, VaultCreatedEvent.OutputObject>;
    

      'VaultReleased(uint256,string,address)': TypedContractEvent<VaultReleasedEvent.InputTuple, VaultReleasedEvent.OutputTuple, VaultReleasedEvent.OutputObject>;
      VaultReleased: TypedContractEvent<VaultReleasedEvent.InputTuple, VaultReleasedEvent.OutputTuple, VaultReleasedEvent.OutputObject>;
    
    };
  }