/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Counter } from './Counter.js';
export type { DigitalLegacyVault } from './DigitalLegacyVault.js';
export * as factories from './factories/index.js';
export { Counter__factory } from './factories/Counter__factory.js';
export { DigitalLegacyVault__factory } from './factories/DigitalLegacyVault__factory.js';